# Site settings
title: MXconda - neatly packed MX software
description: Installation of macromolecular crystallography software made easy.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
